x=input()
list0=x.split()
a=int(list0[0])
b=int(list0[1])
c=int(list0[2])
d=int(list0[3])

print (0, a,a+b, a+b+c, a+b+c+d)
print (a, 0, b, b+c, b+c+d)
print (a+b, b, 0, c, c+d)
print (a+b+c, b+c, c, 0, c-d)
print (a+b+c+d, b+c+d, c+d, d, 0)